### ISSUE TITLE
Error: Could not find or load main class ccfindersw.CCFSWLauncher

### ISSUE THREAD

**Issue by Reds123** [YuichiSemura/CCFinderSW#1]
I packaged this project and run the following command

./CCFinderSW D -d ./result/  -l java -o output.txt

but got the following output

Error: Could not find or load main class ccfindersw.CCFSWLauncher

**Comment by YuichiSemura** [comment]
First of all, I must apologize to you. I didn't this issue for two years. Sorry.

Maybe you built this project yourself?
or Did you unzip `CCFinderSW-1.0.zip`?
